# Generated by Django 3.1.2 on 2022-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klass',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=64, unique=True)),
                ('teacher', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('rno', models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
