# Generated by Django 3.1.2 on 2022-04-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('im_no', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='klass',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=64)),
                ('teacher', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('rno', models.CharField(max_length=64, unique=True)),
                ('db', models.BooleanField(default=False)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.image')),
            ],
        ),
    ]
