# Generated by Django 4.0.4 on 2022-05-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('im_no', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='myimage')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('datee', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('presentStudents', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('rno', models.CharField(max_length=64, unique=True)),
                ('db', models.BooleanField(default=False)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.images')),
            ],
        ),
    ]
