# Generated by Django 4.0.4 on 2022-04-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.RemoveField(
            model_name='images',
            name='update',
        ),
    ]
