# Generated by Django 4.0.4 on 2022-04-28 05:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220427_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('date', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('presentStudents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=64)),
            ],
        ),
    ]
