# Generated by Django 4.0.4 on 2022-04-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='presentStudents',
        ),
    ]
