# Generated by Django 4.0.4 on 2022-04-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_date_record_datee_record_presentstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='presentStudents',
        ),
    ]
