# Generated by Django 4.0.4 on 2022-04-28 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_record_presentstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='presentStudents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
