# Generated by Django 4.0.4 on 2022-04-28 05:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_record_presentstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='presentStudents',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
    ]
