# Generated by Django 4.0.4 on 2022-04-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_record_presentstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='presentStudents',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
